auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Strength and Honor. Shadow and Dust.
url: http://fangyijoe.github.io
feed: /atom.xml
author_info: <a href="http://fangyijoe.github.io/">fangyiJoe</a>
